# Generated by Django 5.2 on 2025-04-29 13:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ni', models.PositiveIntegerField()),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(help_text='Ex: +55 (47) 98888-7777', max_length=20, validators=[django.core.validators.RegexValidator(message='Informe um número de telefone válido.', regex='^\\+?[\\d\\s\\-\\(\\)]{10,20}$')])),
                ('data_nascimento', models.DateField()),
                ('data_contracao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('capacidade', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('curso', models.CharField(max_length=255)),
                ('carga_hora', models.IntegerField()),
                ('descricao', models.TextField()),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='app.professor')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaAmbiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
                ('periodo', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], max_length=10)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplina', to='app.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_ambiente', to='app.professor')),
                ('sala_reservada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sala', to='app.sala')),
            ],
        ),
    ]
